version: '2'

services:
  db:
    image: mysql
    volumes:
      - ./testapp:/home
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      TZ: Asia/Tokyo

  app:
    image: rails:5
    build:
       context: ./testapp
       dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
    - ./testapp:/home
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3000:3000"
    links:
      - db:db
